version: '3'
services:
  express_server:
    build:
      context: .
      target: express_server
    image: to_to_list_express_server
    stdin_open: true
    tty: true
    ports:
      - "3030:3030"
    volumes:
      - ./express_server:/home/node/app
      
  
  react_server:
    build:
      context: .
      target: react_server
    image: to_to_list_react_server
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./react_server:/home/node/app
  

  database:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

# vi:et:ts=2:sw=2:cc=80
